
# Specify input file and output folders
input_file: "input/c2iBladder_tumor_bam_files_SOFTLINKS.tsv" # "input/c2iBladder_plasma_bam_files.tsv"
sample_ID_column: 'Sample_ID'
filepath_column: 'input_file'
preprocess_output: "results/c2iBladder/ichorCNA/plasma/preprocess/" # "ichorCNA/preprocess/"
ichorCNA_output: "results/c2iBladder/ichorCNA/plasma/output/" # "ichorCNA/output"
log: "logs/c2iBladder/plasma/" # "ichorCNA/logs/"

# readCounter parameters
readCounterScript: "ichorCNA/software/hmmcopy_utils/bin/readCounter" # The directory of the readCounter script. Downloaded from: "https://github.com/shahcompbio/hmmcopy_utils"
windowSize: 1000000 #1Mb
mappingQuality: 20
chromosomes: "chr1,chr2,chr3,chr4,chr5,chr6,chr7,chr8,chr9,chr10,chr11,chr12,chr13,chr14,chr15,chr16,chr17,chr18,chr19,chr20,chr21,chr22,chrX,chrY" #1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,X,Y"

# ichorCNA parameters
ichorCNA_folder: "ichorCNA/software/ichorCNA"
ichorCNA_script: "/scripts/runIchorCNA.R" 

## Required
ichorCNA_gcWIG: "/inst/extdata/gc_hg38_1000kb.wig"
ichorCNA_mapWIG: "/inst/extdata/map_hg38_1000kb.wig"

## Panel of normals
PanelOfNormalsScript: "/scripts/createPanelOfNormals.R"
NormalsExist: False #'True' if you have actual normal samples

## Optional
ichorCNA_genomeBuild: hg38
ichorCNA_genomeStyle: UCSC #default: NCBI
ichorCNA_ploidy: c(2) # default: 2 
ichorCNA_normal: "c(0.95, 0.99, 0.995, 0.999)" # default: 0.5
ichorCNA_maxCN: 3 # default: 7
ichorCNA_centromere: "/inst/extdata/GRCh38.GCA_000001405.2_centromere_acen.txt" # default: hg19 version from ichorCNA package
#ichorCNA_normalPanel: "/inst/extdata/HD_ULP_PoN_1Mb_median_normAutosome_mapScoreFiltered_median.rds" # default: NULL
ichorCNA_includeHOMD: FALSE # default: False
ichorCNA_chrs: c(1:22, \"X\") # default: "c(1:22, \"X\")"
ichorCNA_chrTrain: c(1:22) # default: [c(1:22)]
ichorCNA_estimateNormal: TRUE # default: True
ichorCNA_estimatePloidy: TRUE # default: True
ichorCNA_estimateScPrevalence: FALSE # default: True
ichorCNA_scStates: "NULL" # default: NULL

